name: Compila y Genera PDF

on: 
  push:

jobs:
  compila:
    runs-on: ubuntu-latest

    steps:
      - name: ⏳Hacer checkout - Clonar el repositorio actual
        uses: actions/checkout@v4.2.2

      - name: Instalar .NET en el runner
        uses: actions/setup-dotnet@v3.4.2
        with:
          dotnet-version: '9.0.x'

      - name: Instalar dependencias
        run: dotnet restore

      - name: Compilar
        run: dotnet build --no-restore

  crear-pdf:
     runs-on: ubuntu-latest

     steps:
       - name: ⏳Hacer checkout - Clonar el repositorio actual
         uses: actions/checkout@v4.2.2
       - uses: BaileyJM02/markdown-to-pdf@v1.2.0
         with: 
           input_dir: docs
           output_dir: pdfs

           build_hmtl: true

       - name: Upload artifact 
         uses: actions/upload-artifact@v4
         with:
           name: readme
           path: generated
        

          

          
       

        
